addons:
    apt:
        packages:
            - cmake
            - gfortran

python:
    - "3.5"

script:
    - mkdir build tests
    - cd build
    - cmake ..
    - make

after_script:
    - cd ../scripts
    - python3 run_tests.py --cores 2 --exec ../build/HAZ --rtol 0.001

