
branches:
    # whitelist
    only:
        - master
        - develop

# Configure git linebreaks
init:
    - git config --global core.autocrlf input

install:
    # Change mirrors for better performance
    - C:\msys64\usr\bin\pacman -S pacman-mirrors
    # Update core packages
    - C:\msys64\usr\bin\pacman -Syu
    # Restart MSYS2
    - update-core
    - C:\msys64\usr\bin\pacman -S mingw-w64-{i686,x86_64}-cmake mingw-w64-{i686,x86_64}-gcc-fortran

build_script:
    - mkdir build tests
    - cd build
    - cmake ..
    - make 
