
branches:
    # whitelist
    only:
        - master
        - develop

# Configure git linebreaks
init:
    - git config --global core.autocrlf input

install:
    # Add msys to path
    - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
    # Change mirrors for better performance
    - pacman -S --noconfirm pacman-mirrors
    # Update core packages
    - pacman -Syu --noconfirm
    # Restart MSYS2
    - update-core
    # Install dependencies
    - pacman -S --noconfirm mingw-w64-{i686,x86_64}-cmake mingw-w64-{i686,x86_64}-gcc-fortran

build_script:
    - mkdir build tests
    - cd build
    - cmake ..
    - make 
